### ISSUE TITLE
how did you annotate vertices of 3d-shape?

### ISSUE THREAD

**Issue by linpeisensh** [nileshkulkarni/acsm#1]
Thank you for your excellent work!

I have read your paper and have questions: how did you annotate vertices of 3d-shape, e.g. horse?

**Comment by nileshkulkarni** [comment]
We manually labeled an approximate location of the vertex corresponding to the keypoint.

[Here](https://drive.google.com/drive/folders/1OQ_L50ymgfGtEeJQiiRH_ClR-cWHosF1) are our labels for the few categories we used.

**Comment by linpeisensh** [comment]
Thank you for your reply!

My expression may make you misunderstood. 

Could you tell me, how would you group the vertices of a template shape into  functional parts?

What's the meaning of the color in Figure 2? Does it mean that the darker the color is, the closer the assignment to 1?

And is it enough for each part only one transformation? As you can see in the following picture, with a simple rotation, the neck is disconnected with the body.
![image](https://user-images.githubusercontent.com/52672986/83763938-92a8a180-a679-11ea-8237-56f79bae6db6.png)

**Comment by nileshkulkarni** [comment]
Hi,
I'm sorry for the delayed response. 

I used Autodesk mesh-mixer to create vertex groups. Yes, your interpretation of figure 2 is correct.

We found that one transformation per part is sufficient to model the major articulations in quadrupeds. We also perform blending along with applying per-part transformations.

Sample pseudo-code: 
Let's assume the horse has 7 parts  (4 legs, 1 head, 1 neck, and the body). Also we have a hierarchy between parts.  
(Parent --> Child)
Body --> Legs
Body --> Neck
Neck --> Head
1. For every vertex assign an \alpha (1 x 7 vector) that maintains the membership of the vertex to the group. sum(alpha) = 1
2. Create 7 copies of the vertices corresponding to each part and then apply the transformation for the children followed by the transformation of the parent.
3. Combine all the vertices using the \alpha from 1.

I hope this helps!

**Comment by linpeisensh** [comment]
Thank you for your reply! It really helps.

Another question:
How did you get every vertex assignment? 
In my opinion, it's from the distance from some picked vertices and sample it with Gaussian, but it's very hard to divide hind leg and tail.
Do you have any suggestion?
![image](https://user-images.githubusercontent.com/52672986/84870839-14d49500-b080-11ea-973a-26a45bc87ee0.png)

**Comment by nileshkulkarni** [comment]
I used Autodesk MeshMixer to basically label the vertices into different categories. If you have access to that software it is very simple to use it.
In summary, it allows you to manually select the vertices you want to label as that part. This annotation process takes about 15mins per model. I tried using some automatic techniques but it is hard to get them separated. If it helps, [here](https://drive.google.com/drive/folders/1H52Z2QQX7_q03aAnEsOZxw3GrF6YshKo) are my parts and the code that can generate the alpha. 

Please edit the L559 and run the code as `python convert_to_parts.py`

horse_parts.obj contains all parts as dis-connected components, and the part_names.txt provides the names for those disconnected components.

Best, 
Nilesh

**Comment by linpeisensh** [comment]
Thank you for your reply!

I will try it.

**Comment by linpeisensh** [comment]
Hello, I have run your code and get the soften assignment.
But as you can see, the result is still weird.
![image](https://user-images.githubusercontent.com/52672986/85453347-0e707c80-b59c-11ea-959a-5a4e801be267.png)
1.For example, neck rotates pi/6, head rotates -pi/2, for head **Tl** = pi/6. And head rotates first Tk' then Tl. Am I right?
![image](https://user-images.githubusercontent.com/52672986/85453830-95255980-b59c-11ea-82c2-5ff493c03884.png)

2.And I also want to know, what about the Tk of rotation center of head in my example? And what is your rotation center for each part?

I look forward to your answer!

**Comment by nileshkulkarni** [comment]
1. I think you are interpreting it right.

2. The rotation center is the average of all the vertices on the boundary connecting the two parts. In the case of head, consider all the vertices that are connecting the head to the neck and choose the mean vertex as the rotation center about which the y-axis passes and rotations are performed.

Best,
Nilesh

**Comment by linpeisensh** [comment]
Thank you for your reply!

Another questions:
How can we use this alpha? 
![image](https://user-images.githubusercontent.com/52672986/85581565-fc92e600-b63c-11ea-8281-43134f67a70e.png)
1.Does this alpha work on the rotation angle or the whole Tk (or simply to rotation) ? 

2. Does this sum notation means this vertex rotates 7 times or sum up the weighted rotation matrix and rotates one time?

3. Do we need to check the rotation center every time after a rotation?

Best,
Peisen Lin

**Comment by nileshkulkarni** [comment]
1. Alpha  N_verts x N_parts size matrix. So it basically linearly weighs the location of the same the vertex resulting from different transformations applied to it.e
2. Yes, you are right. Every vertex is rotated 7 times, and then a weighted average is taken using alpha.
3. No, the rotation center is defined by the base template (since the base template does not change you only need to compute it once)

**Comment by linpeisensh** [comment]
3. for your 2., are 7 times rotations from the original vertex position then weighted them and get new position of this vertex?

**Comment by nileshkulkarni** [comment]
First, you rotate the head by pi/2 and then you rotate the by the necks rotations., yes every vertex is rotated by the transformation of the part (which is T_{k} as in equation 4) remember we do not predict T_{k} directly we predict the local transforms for the parts.

I think in your example pi/2  and pi/6 represent the local transformation for neck and head. So you should compute the global transforms for the head as R_{head_global} = R_{neck}* R_{head}. Similarly, create another set of vertices by rotating using just the R_{neck} and then do a linear combination of them using the alpha.

**Comment by linpeisensh** [comment]
I am still unclear, should I R_{neck}* R_{head} first or should I get mean of 7 rotation first and then rotate with R_{neck}?

**Comment by nileshkulkarni** [comment]
Here is the idea. Let's assume we have three parts body, neck, and head.
So T' <sub>neck</sub> and T'<sub>head</sub>  represent local part transforms. Let us assume that T'<sub> body </sub> is Identity. 

Now let T<sub>head</sub> = T' <sub>neck</sub> * T' <sub>head</sub> represents the global transform, and T<sub>neck</sub> = T'<sub>neck</sub> since neck's parent has identity transform. T<sub> body </sub> = T' <sub> body </sub>

With these parts, we can create a new set of vertices as follows

v<sub>head</sub> = T<sub>head</sub> * v
v<sub>neck</sub>  = T<sub>head</sub> * v
v<sub>body</sub> = T<sub>body</sub> * v

v<sub>blended</sub> = alpha<sub>head</sub> * v<sub>head</sub> + alpha<sub>neck</sub> * v<sub>neck</sub> + alpha<sub>body</sub> * v<sub>body</sub>

**Comment by linpeisensh** [comment]
Is this vblended the final vertex? Because I get a very weird mesh with this function(neck rotates pi/3):
![image](https://user-images.githubusercontent.com/52672986/85725181-2c052980-b6f5-11ea-8d86-72a6884e229e.png)
here is my code:
R = []
for i in range(len(current_corr)): #current_corr rotation center
    part_chain = [i]
    while part_parent[part_chain[0]] != "#":
        part_chain.insert(0, part_parent[part_chain[0]])
    cR = np.eye(3)
    for j in part_chain:
        cR = cR.dot(quaternion_to_rotation(transform[j]["R"]))
    R.append(cR)
R = np.array(R)
for i in range(len(verts)):
    nverts = []
    for k in range(len(current_corr)):
        nvert = np.dot(R[k], verts[i] - current_corr[k]) + current_corr[k] + transform[k]['t']
        nverts.append(ass[i][k] * nvert)
    nverts = np.array(nverts)
    verts[i] = np.sum(nverts, axis=0)
Thank you very much!

**Comment by linpeisensh** [comment]
I think I need to translate the head after neck rotation, but the rotation changed and not equal to Rneck.dot(center_head).  How can get this new center?

**Comment by linpeisensh** [comment]
This v = vertex - rotation center of each part, is it right?

**Comment by nileshkulkarni** [comment]
Yes, If you subtract the rotation center you do have to add it back after you perform the rotation. I'm abstracting out everything into the transform T

**Comment by linpeisensh** [comment]
so in practice we learn only rotation and translation of each part and get a final vertex like

> v_blended = alpha_head * v_head + alpha_neck * v_neck + alpha_body * v_body

> v_head = R_head * v + T
this v is vertex that is not subtracted by rotation center. Is it right?

**Comment by linpeisensh** [comment]
If I am not misunderstood, there is no need to get rotation center of each part? Since you put all into t.

**Comment by linpeisensh** [comment]
Thank you for your advice. I finally finish this part.
