### ISSUE TITLE
The PCK under reprojection for horse

### ISSUE THREAD

**Issue by linpeisensh** [nileshkulkarni/acsm#4]
Thank you for your excellent work!

I have run your acsm code and found the PCK under reprojection for horse is much smaller than you show in your paper. The PCK transfer is fine.
![image](https://user-images.githubusercontent.com/52672986/89131902-92f5d980-d510-11ea-853c-a1a33e5377df.png)
as you can see in the following picture, the predict key points are not so close to the ground truth.
![0075_img_kp](https://user-images.githubusercontent.com/52672986/89131938-c7699580-d510-11ea-96ba-7e0793ef8ba1.png)
![0075_img_kp_project](https://user-images.githubusercontent.com/52672986/89131939-c89ac280-d510-11ea-9f7b-f519a2cef5dd.png)
I have run this to test:
python -m acsm.benchmark.pascal.kp_project --name=acsm_horse_8parts --category=horse --parts_file=acsm/part_files/horse.txt --use_html --dl_out_pascal=True --dl_out_imnet=False --split=val --num_train_epoch=400 --num_hypo_cams=8 --env_name=acsm_horse_8parts_pck_val --multiple_cam=True  --visuals_freq=5 --visualize=True --n_data_workers=4 --scale_bias=0.75 --resnet_style_decoder=True --resnet_blocks=4
Have I done something wrong?

**Comment by nileshkulkarni** [comment]
Hi @linpeisensh,

I think the command is missing two parameters `--el_euler_range=20 --cyc_euler_range=20`  that is the reason I think the numbers are so low. Hope that fixes it. I will edit the command on the readme. Thanks for pointing out.

Best,
Nilesh

**Comment by linpeisensh** [comment]
Thank you!

It works.
