### ISSUE TITLE
Inference on other parametric models

### ISSUE THREAD

**Issue by raincrash** [nileshkulkarni/acsm#5]
Hi, thanks for the great publication. A quick question on using a-csm on other custom parametric models. For _inferencing_ on categories not present in CUBS, is there a way to use the given template models and annotations?

**Comment by nileshkulkarni** [comment]
Hi @raincrash, 

I'm slightly confused about your question. CUBS only has bird images. Could be a bit more specific so that I can answer your question better. 

Thanks,
Nilesh

**Comment by raincrash** [comment]
Hi, @nileshkulkarni sorry for the late reply. Yes, I wanted to infer on images that are not on the CUBS dataset, but also on a different parametric model, for eg airplanes. Do I need to train for each type of parametric model or is there was a way to infer on airplane images and model directly?

**Comment by nileshkulkarni** [comment]
Hi @raincrash,
Ours is category-specific model so it will not work on categories it is not trained on. To train on a new category you would have to create a first a category-specific parameterization and then train CSM or ACSM style model to infer the surface parameterization. It would incorrect to run inference on airplanes while using weights from a model that is trained on birds.

**Comment by raincrash** [comment]
Got it! Thanks. I'll close the issue.
