### ISSUE TITLE
Is it possible to share the full models for cow and sheep?

### ISSUE THREAD

**Issue by statho** [nileshkulkarni/acsm#7]
Hi,

Thanks for your excellent work and contribution to the community!

I noticed the models for cow and sheep are missing (the respective folders in /cachedir/models are empty for these 2 animals). Is it possible to share the content of those folders?

Thanks a lot in advance!

Best,
Anastasis

**Comment by nileshkulkarni** [comment]
The models for the sheep and cow are updated to the cachedir here [https://www.dropbox.com/s/8zo5ohwhv99efqr/cachedir.tar.gz?dl=0]

Thanks,
Nilesh

**Comment by statho** [comment]
Thanks a lot Nilesh :)
