### ISSUE TITLE
Annotations for cow and sheep

### ISSUE THREAD

**Issue by statho** [nileshkulkarni/acsm#8]
Hi Nilesh,

Is it possible to share the annotation and data used for the cow and sheep categories used (just like you did for the horse category)?

Thanks a lot in advance!

Best,
Anastasis

**Comment by nileshkulkarni** [comment]
Hi,
Here is an updated [link](https://www.dropbox.com/s/8zo5ohwhv99efqr/cachedir.tar.gz?dl=0) with the annotations included for cow and sheep.

Thanks,
Nilesh
